### ISSUE TITLE
output of generate_devicemodel_mapping_file is hardcoded

### ISSUE THREAD

**Issue by morinpa** [jasoncdavis/import2netbox#1]
This function always outputs these two devices only because of this line 

...
    device_mapping = """---
devices:
"""
    unique_cc_devicetypes = ['C9KV-UADP-8P', 'C9136']
    for devicetype in unique_cc_devicetypes:
...

so this line can just be commented (or deleted)  

#unique_cc_devicetypes = ['C9KV-UADP-8P', 'C9136']

**Comment by jasoncdavis** [comment]
created branch issue1 with fix to remove hard-coded device-types;  Also added minor doc updates
