### ISSUE TITLE
sample csv file

### ISSUE THREAD

**Issue by ashokthangaraj** [jasoncdavis/import2netbox#3]
Hi Jason,

Can you share me a sample csv file format to try this.
 python import_csv2nb.py -f filename.csv

**Comment by jasoncdavis** [comment]
Hey Ashok - my apologies!  Thought I dropped a sample in there.  I had one waiting in the dev folder.  Thanks for letting me know!  I've uploaded it into this repo.
https://github.com/jasoncdavis/import2netbox/blob/main/excelcsv2netbox-template.xlsx

Fill it out in Excel, as convenient, then save (each tab) as a separate CSV file, as needed.

**Comment by jasoncdavis** [comment]
It appears Ashok was able to get the file, so closing the issue.
